name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python 3.10
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install system dependencies
    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git build-essential zlib1g-dev \
        libncurses5-dev libncursesw5-dev libsqlite3-dev libreadline-dev libffi-dev \
        libssl-dev libbz2-dev openjdk-11-jdk unzip

    # 4️⃣ Install Buildozer and Cython
    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade buildozer cython

    # 5️⃣ Ensure buildozer.spec exists
    - name: Check or Init buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    # 6️⃣ Build APK with verbose logging
    - name: Build APK
      run: |
        buildozer -v android debug

    # 7️⃣ Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: StoreScannerApp-APK
        path: bin/*.apk
